### ISSUE TITLE
`realpath` doesn't exist on OSX 

### ISSUE THREAD

**Issue by barelyhuman** [egoist/bina#3]
OSX doesn't have `realpath` by default and needs the user to install `coreutils` either via brew or something else. 
This can be polyfilled if we want to avoid that. 

Also , there's a minor typo in the script, it's supposted to `browser_download_url` and not `url`

**Comment by barelyhuman** [comment]
PR for the same: https://github.com/egoist/bina/pull/4

**Comment by egoist** [comment]
actually `url` should work when we have `application/octet-stream` in header https://docs.github.com/en/rest/reference/repos#get-a-release-asset

**Comment by barelyhuman** [comment]
Got it, will need to debug the curl url again for the same, i'll update on what could be causing this
