### ISSUE TITLE
Weird ouput

### ISSUE THREAD

**Issue by Aslemammad** [egoist/bina#8]
Hey, I'm excited about this project. Thank you for your fantastic stuff, @egoist.

I encounter this output (when I try installing dum) both in st (suckless terminal) and alacrity.
```
 bagher ~ $ curl -sSL https://bina.egoist.sh/egoist/dum | sh

\x1B[33m  ==>\x1B[39m Using auto generated config because egoist/dum doesn't have a bina.json file in its release
\x1B[33m  ==>\x1B[39m This might not work for some projects
\x1B[94m  ==>\x1B[39m Resolved version latest to v0.1.12
\x1B[94m  ==>\x1B[39m Downloading asset for linux amd64
```
I'd like to contribute to this project, it'd be really good if you can give me a hint about this output.

**Comment by egoist** [comment]
https://github.com/egoist/bina/blob/dbc01bad4174e5e873723df7a8cdc1b73d4b8bcd/make_sh.ts#L62

these ANSI color sequences are not properly supported in some terminals, should be updated to a more compatible version.

**Comment by Aslemammad** [comment]
Thanks for the hint; I'm going to work on it.

**Comment by egoist** [comment]
https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux this one should probably work

**Comment by Aslemammad** [comment]
Thanks for the merge @egoist.
